### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-streets#120]
Related to #112

Kick the tires in various browsers and OS, flag issues if any arise, close if we are reasonably comfortable that there are no glaring issues.

**Comment by allthesignals** [comment]
@andycochran I think you did some of this, what'd you find? #112 was a result of this?

**Comment by andycochran** [comment]
I did look at BrowserStack and fix some CSS issues that arose from that. But #112 already existed. I think this browser testing is ongoing and we should look at the app in BrowserStack again at the end of the sprint.
