### ISSUE TITLE
Improved load state

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-streets#131]
I noticed in the Font Awesome docs this nice pattern… 

![image](https://user-images.githubusercontent.com/409279/39195830-a0a221d4-47ae-11e8-9d62-b130a7c880af.png)

… which made me think: 

It'd be great to know which layers are causing the map to be in a loading state and indicate in the layer menu. We could detect which are on/off before and after the load event and style them appropriately.

**Comment by jpiacentinidcp** [comment]
migrated to ADO
