### ISSUE TITLE
Research Intersection Search

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-streets#21]
- [ ] Intersection Search

User wants to search for an intersection by cross street names. This will have to be a typeahead search.

**Comment by allthesignals** [comment]
Possibilities:
 - Add street intersections search to GeoSearch? 
 - Use GeoClient directly
 - Create point dataset, and search through Carto SQL API.

**Comment by jpiacentinidcp** [comment]
migrating to ADO
