### ISSUE TITLE
Transition symbology for basemap when aerials are on

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-streets#226]
-when aerials are turned on, street lines and boundaries are difficult to see
-transition this symbology to a different style when aerials are turned on

**Comment by trbmcginnis** [comment]
User Feedback from Isaac Dayan (Metropolitan Properties), idayan@metropropertiesnyc.com on 8/14:

"When using Aerial Imagery, the Street/Avenue names disappear. Any way to fix this or am I doing something wrong?"

Zola should have street labels overlaid on the aerials so users can see street names or be able to switch the base map from streets to aerials while maintaining the street labels.

Aerial View
image

Street View
image

**Comment by trbmcginnis** [comment]
FEEDBACK: Two things to make the aerials display better.
We need to turn off the alteration map layer when someone turns on the aerial layer. We can allow them to turn it back on, but it overlays a transparency on the aerial that makes it hard to read the aerial.

Next, we need to make the basemap lines yellow to show up against the aerial.

**Comment by trbmcginnis** [comment]
Andrew English: Also tax lots gets washed out when aerials are turned on. The user will routinely reference the tax lots and aerials together so these layers need to be legible when turned on at the same time.

**Comment by trbmcginnis** [comment]
RonthePlanner: I inquired about this as well via e-mail. "For these eyes - the tax lines are too light. Street lines should be visible at all times - the need to hover over street lines in aerial view is very limiting.

Overall, these two items makes this much less useful than the Zoning Application for me"

**Comment by trbmcginnis** [comment]
srlenard: 

Change mapped streets, unmapped streets, and street treatment lines to show yellow when arials are turned on. Yellow shows well against both light and dark portions of photos.

**Comment by jpiacentinidcp** [comment]
feature request added to ADO [https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/13714]
