### ISSUE TITLE
Application does not respond to clicks

### ISSUE THREAD

**Issue by srlenard** [NYCPlanning/labs-streets#257]
This has been happening on the site for a long time.  Sometimes (maybe 25% of the time) I bring up the site and click on a lot or an alteration map polygon and the wheel at the bottom right spins but nothing happens.  Not sure what it could be.

Thanks, 

Steven

**Comment by hannahkates** [comment]
Hi @srlenard I'm doing to some GitHub cleanup. Has this still been an issue for you?

**Comment by jpiacentinidcp** [comment]
issue is no longer present. closing out
