### ISSUE TITLE
Latitude Longitude parameters reversed

### ISSUE THREAD

**Issue by boggyfresh** [NYCPlanning/labs-streets#258]
#### Instead URL parameter "lat=" equals longitude coordinate and "lng=" equals latitude coordinate

Example Link: https://streets.planning.nyc.gov/feedback?lat=-73.9629&lng=40.7188&zoom=18.5

Google Map link with coordinates: https://www.google.com/maps/@40.7188,-73.9629,20z

**Comment by chriswhong** [comment]
Thanks for pointing this out!

**Comment by rtblair** [comment]
Added to backlog. AB#3745
