### ISSUE TITLE
Update ZoLa URL

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-streets#264]
Once the ZoLa URL refactor is done, we need to update the ZoLa URL here: https://github.com/NYCPlanning/labs-streets/blob/c10cb62feb41be2fa514fea7f544f88d8118c3ec/app/templates/components/map-popup-content.hbs#L44

**Comment by gregsadetsky** [comment]
Just to comment on this, the present [City Map](https://streets.planning.nyc.gov/about) has this issue. The hyperlink to the `zola.planninglabs.nyc` domain does not work, as the SSL certificate is invalid. The domain should be replaced with `zola.planning.nyc.gov`

**Comment by allthesignals** [comment]
Closed by https://github.com/NYCPlanning/labs-streets/pull/272 - sorry for the delay!
