### ISSUE TITLE
Tax Block & Lot Search Bug

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/labs-streets#299]
#### What should happen:
Searching for Tax Block or Tax Lot function should identify and zoom to valid tax block or lot when entered into the BBL lookup

#### What happened instead:
Nothing, search results do not zoom to block or lot and no error messages

#### How to reproduce this bug:
Block search
1. Enter borough - 'Manhattan (1)'
2. Enter block - '47'
3. Click go to block

-or-
Lot search
1. Enter borough - 'Manhattan (1)'
2. Enter block - '47'
3. Enter lot - '7501'
4. Click go to lot

#### Browser(s) and Device(s) observed on:
Google Chrome, Dell PC

**Comment by rtblair** [comment]
Thanks, @croswell81, and sorry for just noticing this now. Tracking further work with AB#3743
