### ISSUE TITLE
store.createRecord does not apply custom transforms

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-streets#65]
We are using a transform to enforce basic object structure for mapbox layer definitions, but transforms aren't applied when using `createRecord` on the store. This has implications for tests, results in some surprises, and requires some defensive programming in the layer model (see delegateVisibility method). Opening issue to put a pin in this - we should find a better way to enforce basic defaults of mapbox layer definitions.

**Comment by jpiacentinidcp** [comment]
no longer relevant
