### ISSUE TITLE
Preserve click as query param

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-streets#79]
Consider preserving the popup for map amendments in url

**Comment by allthesignals** [comment]
This is getting complicated. We have a lot of asynchronous stuff happening for different reasons in the popup. First, we query a database for some information. Then we locally query the map using queryRenderedFeatures. Both of these queries accept different coordinates, geographic and cartesian, so we need to store those point sets in the URL.

After all that, we do data munging both in the server and in the client. This happens downstream, inside the component, rather than in a callback in the promise. 

It's hard to check for whether there is an _incoming_ query param and have that be overwritten by a default by the time the controller comes into play. Query params have default values, and those are applied afterwards. So we can't check for whether incoming QPs are present except in `beforeModel` or `model`. Basically we would need to check whether the default value is there, which is awkward to me... check for non-default QPs in the mapLoaded event could work. 

I think this will require taking a fresh new look at the way the popup works and seeing how we can improve the overall approach to it.

**Comment by allthesignals** [comment]
I'm gonna think about this some more and try to refactor things a bit so we can solve this more elegantly

**Comment by chriswhong** [comment]
I don't think this is is a high priority, it would be nice, but not that important I think.

**Comment by jpiacentinidcp** [comment]
migrated to ADO
